Remove dyn buf from p2p reader
tezedge/tezedge pull request #501
Opened 2021-03-16 08:38 UTC by vlad9486

2021-03-17 08:31 UTC, bkontur requested changes
@vlad9486 
Vlad, please check a lots of older clippy stuff in this PR,
and rebase to develop also

2021-03-18 10:23 UTC, bkontur commented on tezos/encoding/src/binary_reader.rs
> +        let new_length = buf_slice.len() + (*buf).len();
@vlad9486 
please, Vlad

2021-03-18 10:25 UTC, bkontur requested changes
@vlad9486 @akoptelov 
I guess, there is just one commetnt with that arithemtics still unresolved

2021-04-02 08:08 UTC, vlad9486 commented on tezos/encoding/src/binary_reader.rs
> +        let new_length = buf_slice.len() + (*buf).len();
Sorry for late respond. I updated the code. I see no need to do checked arithmetic and `safe!`. Refactored my code to make it obvious.

2021-04-02 10:59 UTC, bkontur commented
@vlad9486 
please, check this panics and add Err handling instead:

https://github.com/simplestaking/tezedge/pull/501/files#diff-88ff5d321cc7a89f7e1c9ceaeff8e1971bfcf02315ebc32c73817f4e797caf5fR1066

https://github.com/simplestaking/tezedge/pull/501/files#diff-88ff5d321cc7a89f7e1c9ceaeff8e1971bfcf02315ebc32c73817f4e797caf5fR1094

https://github.com/simplestaking/tezedge/pull/501/files#diff-88ff5d321cc7a89f7e1c9ceaeff8e1971bfcf02315ebc32c73817f4e797caf5fR1104

2021-04-02 11:00 UTC, bkontur requested changes
@vlad9486 
please, check these panics and add Err handling instead:

https://github.com/simplestaking/tezedge/pull/501/files#diff-88ff5d321cc7a89f7e1c9ceaeff8e1971bfcf02315ebc32c73817f4e797caf5fR1066

https://github.com/simplestaking/tezedge/pull/501/files#diff-88ff5d321cc7a89f7e1c9ceaeff8e1971bfcf02315ebc32c73817f4e797caf5fR1094

https://github.com/simplestaking/tezedge/pull/501/files#diff-88ff5d321cc7a89f7e1c9ceaeff8e1971bfcf02315ebc32c73817f4e797caf5fR1104

2021-04-02 11:06 UTC, vlad9486 commented
@bkontur There are tests. Panic in test is ok.

2021-04-02 11:10 UTC, bkontur commented
> 
> 
> @bkontur There are tests. Panic in test is ok.

ok, right :), I didnt realize it it in test,

@akoptelov 
Alex, please, could you also do a quick check?

2021-04-02 11:15 UTC, vlad9486 commented
@bkontur We can do this
```
        encode_value(&mut data, &value, &encoding)
            .expect_err("Encoding an empty enum value should not succeed");
```
Clippy will be happy (I hope), and code is more clear

2021-05-19 20:18 UTC, bkontur commented
@vlad9486 
Vlad could you please rebase and squash this?

2021-05-19 20:49 UTC, akoptelov commented
@bkontur @vlad9486 Does it make much sense in doing this now, and then trowing away as nom is fully adopted?

2021-05-19 21:06 UTC, bkontur commented
> 
> 
> @bkontur @vlad9486 Does it make much sense in doing this now, and then trowing away as nom is fully adopted?

I dont know :), you tell me :D,
if this will go away and it does not fix anyhting critical, we can close it

2021-05-31 06:01 UTC, vlad9486 commented
@bkontur yes, let's close it.

2021-05-31 06:01 UTC, closed without merging