Implement the tezedge baker
tezedge/tezedge pull request #916
Opened 2022-01-12 11:21 UTC by vlad9486

2022-05-27 11:26 UTC, akoptelov requested changes
@vlad9486 This is not final review, and all the comments except one are not necessary at all, but the last one, about long lines, is quite critical. Will you be able to fix that?

2022-05-27 11:26 UTC, akoptelov commented on apps/baker/src/machine/state.rs
> +        let map_str = r#"{"committee_size":7000,"ours":["tz1QeSZGJWXfghVHcz737ELaLk9LodSx5Quv"],"level":568272,"delegates":{"568271":{"tz1KkJtLB9pMdLKNpVRNZw9zmysrxKmYcRGU":"[189,268,308,322,334,390,
This kills highlighting in my Emacs. Can you move it out to an external file?

2022-05-27 18:08 UTC, tizoc commented on crypto/src/hash.rs
> +    pub const SEED_ED25519: [u8; 4] = [043, 246, 078, 007];
There are some clippy warnings here, it doesn't like the leading 0s

2022-05-30 11:08 UTC, vlad9486 commented on apps/baker/src/machine/cycle_nonce.rs
> +        let cycle = level / self.blocks_per_cycle;
Oh...

2022-05-30 11:08 UTC, vlad9486 commented on apps/baker/src/machine/actions.rs
> +    fn is_enabled(&self, state: &S) -> bool {
Let it be for now.

2022-05-30 11:09 UTC, vlad9486 commented on shell_automaton/tests/action_fuzz.rs
> -    *FUZZER_ARGS.write().unwrap() = Some(builder.arguments.clone());
I don't know. It is my biggest concern, it doesn't compile. @dkuehr we need your help.

2022-05-30 11:09 UTC, vlad9486 commented on apps/baker/Cargo.toml
> +edition = "2018"
No reason. Try to remove and see what happen.

2022-05-30 11:11 UTC, vlad9486 commented on apps/baker/src/machine/effects.rs
> +            // TODO: investigate it
Sometimes `monitor_operations` return "connection reset by peer", it will work if I retry. I don't know why it is so.

2022-05-30 11:13 UTC, vlad9486 commented on apps/baker/src/machine/cycle_nonce.rs
> +        let cycle = level / self.blocks_per_cycle;
Baker is protocol specific. Anyway, we will need a new baker version for the new protocol.

2022-05-30 13:06 UTC, akoptelov commented on crypto/src/blake2b.rs
> +///  1 2  3 4 5 5 5 5
Rust is very sensitive to this kind of graffiti. It makes `cargo test` to fail.

2022-05-30 15:35 UTC, merged